name: Liascript Automation

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  run_liascript_automation:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This grants permission to create and update releases

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Or your preferred Node.js version

    - name: Install Node.js dependencies
      run: npm install

    - name: Generate Liascript PDF
      run: npm run generate-pdf # This runs your script/generate-pdf.js

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: ${{ success() }} # Only create a release if the generation step succeeded
      with:
        tag_name: ${{ inputs.version }}
        name: Liascript Release - ${{ inputs.version }}
        body: |
          Automated release of Liascript content for version ${{ inputs.version }}.
          Includes generated PDF from `week03_.md`.
        draft: false
        prerelease: false
        files: dist/week03_lesson.pdf # Specify the exact file to upload, or dist/* for all
